warehouse:
  database: sequencescape_warehouse
  host:     seqw-db
  port:     3379
  user:     warehouse_ro
gclp_warehouse:
  database: gclp_mlwarehouse
  host:     vm-mii-gclp
  port:     3435
  user:     insert_username
  password: insert_password
  